---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: '8.5.2'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: grafana
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values: # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
    replicaCount: 1
    image:
      # -- The Docker registry
      registry: europe-west2-docker.pkg.dev/cicd-438419
      # -- Docker image repository
      repository: monitoring/grafana
      # Overrides the Grafana image tag whose default is the chart appVersion
      tag: "11.2.1"
      sha: ""
      pullPolicy: IfNotPresent

      ## Optionally specify an array of imagePullSecrets.
      ## Secrets must be manually created in the namespace.
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      ## Can be templated.
      ##
      pullSecrets: []
      #   - myRegistrKeySecretName

