apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
images:
- name: ghcr.io/fluxcd/helm-controller
  newName: europe-west2-docker.pkg.dev/cicd-438419/flux-system/helm-controller
  newTag: v1.1.0
- name: ghcr.io/fluxcd/kustomize-controller
  newName: europe-west2-docker.pkg.dev/cicd-438419/flux-system/kustomize-controller
  newTag: v1.4.0
- name: ghcr.io/fluxcd/notification-controller
  newName: europe-west2-docker.pkg.dev/cicd-438419/flux-system/notification-controller
  newTag: v1.4.0
- name: ghcr.io/fluxcd/source-controller
  newName: europe-west2-docker.pkg.dev/cicd-438419/flux-system/source-controller
  newTag: v1.4.1
