---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: '8.5.2'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: grafana
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 1

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir-distributed
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: mimir-distributed
      version: '5.5.0-weekly.310'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: mimir-distributed
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 1

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: loki-distributed
#   namespace: flux-system
# spec:
#   interval: 10m
#   timeout: 5m
#   chart:
#     spec:
#       chart: loki-distributed
#       version: '0.79.4'
#       sourceRef:
#         kind: HelmRepository
#         name: grafana
#       interval: 5m
#   releaseName: loki-distributed
#   targetNamespace: monitoring
#   install:
#     remediation:
#       retries: 3
#   upgrade:
#     remediation:
#       retries: 3
#   test:
#     enable: true
#   driftDetection:
#     mode: enabled
#     ignore:
#     - paths: ["/spec/replicas"]
#       target:
#         kind: Deployment
#   values:
#     replicaCount: 1

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: tempo-distributed
#   namespace: flux-system
# spec:
#   interval: 10m
#   timeout: 5m
#   chart:
#     spec:
#       chart: tempo-distributed
#       version: '1.10.3'
#       sourceRef:
#         kind: HelmRepository
#         name: grafana
#       interval: 5m
#   releaseName: tempo-distributed
#   targetNamespace: monitoring
#   install:
#     remediation:
#       retries: 3
#   upgrade:
#     remediation:
#       retries: 3
#   test:
#     enable: true
#   driftDetection:
#     mode: enabled
#     ignore:
#     - paths: ["/spec/replicas"]
#       target:
#         kind: Deployment
#   values:
#     replicaCount: 1

